[build]
<<<<<<< HEAD
  command = "npm install && node generate-virales.js"
  publish = "."
  environment = { 
    NODE_VERSION = "22",
    YOUTUBE_API_KEY = "AIzaSyDyuMNfrJXOMk4lCwJ7GV70zEP6iwrISuY",
    TIKTOK_MS_TOKEN = "X_LeGXnwuxU3UoagaHwJO772TN7gDLYTt_Vn5rN54jDZsC1B7Sm_6XE8r1DDQfsCCH0l94tRJ1zCp_X7navLQQLcbhGqrzHZF9Ny8nKg0itVq9wB4NR9_NZyvfQluZPShhgKMhuhRETyJj-quBSC5uVU",
    X_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAHvz3AEAAAAA0KKiiRMU8nwQ8ggjG96GDhCZ8T8%3D6BrOF6a4YszLFgLKD1sLlSuhzZdkIFemgCQxo0cTaXAXtjLHnJ"
  }
=======
  command = "node generate-virales.js"
  publish = "."
>>>>>>> db5e9a1 (Proyecto limpio, funcional – vídeos virales YouTube + TikTok)
